# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.CharField(default='', max_length=40),
        ),
    ]
