# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20170706_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='', max_length=254),
        ),
    ]
