# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='media_type',
            field=models.CharField(default='Unknown', max_length=30),
            preserve_default=False,
        ),
    ]
