# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20170711_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='media_type',
        ),
    ]
